export {
  closeDatabase,
  type DatabaseOptions,
  databaseExists,
  getDatabase,
  getDatabasePath,
  initializeDatabase,
  isDatabaseInitialized,
  resetDatabase,
  resetDatabaseInstance,
} from './database.js';
export { CorruptDatabaseError, FutureSchemaError } from './migrations/errors.js';

export {
  CURRENT_VERSION,
  getStoredVersion,
  type Migration,
  runMigrations,
} from './migrations/index.js';
export {
  type AppSettings,
  addFavorite,
  addTaskMessage,
  clearAllConnectors,
  clearAllSkills,
  clearAppSettings,
  clearHistory,
  clearProviderSettings,
  clearTaskHistoryStore,
  clearTodosForTask,
  deleteConnector,
  deleteSkill,
  deleteTask,
  flushPendingTasks,
  getActiveProviderId,
  getActiveProviderModel,
  getAllConnectors,
  getAllSkills,
  getAppSettings,
  getAzureFoundryConfig,
  getConnectedProvider,
  getConnectedProviderIds,
  getConnectorById,
  getDebugMode,
  getEnabledConnectors,
  getEnabledSkills,
  getFavorites,
  getHuggingFaceLocalConfig,
  getLiteLLMConfig,
  getLMStudioConfig,
  getNimConfig,
  getOllamaConfig,
  getOnboardingComplete,
  getOpenAiBaseUrl,
  getProviderDebugMode,
  getProviderSettings,
  getSelectedModel,
  getSkillById,
  getTask,
  getTasks,
  getTheme,
  getTodosForTask,
  hasReadyProvider,
  isFavorite,
  removeConnectedProvider,
  removeFavorite,
  type StoredTask,
  saveTask,
  saveTodosForTask,
  setActiveProvider,
  setAzureFoundryConfig,
  setConnectedProvider,
  setConnectorEnabled,
  setConnectorStatus,
  setDebugMode,
  setHuggingFaceLocalConfig,
  setLiteLLMConfig,
  setLMStudioConfig,
  setMaxHistoryItems,
  setNimConfig,
  setOllamaConfig,
  setOnboardingComplete,
  setOpenAiBaseUrl,
  setProviderDebugMode,
  setSelectedModel,
  setSkillEnabled,
  setTheme,
  updateProviderModel,
  updateTaskSessionId,
  updateTaskStatus,
  updateTaskSummary,
  upsertConnector,
  upsertSkill,
} from './repositories/index.js';
export {
  type ApiKeyProvider,
  createSecureStorage,
  SecureStorage,
  type SecureStorageOptions,
} from './secure-storage.js';
