export const DEV_BROWSER_PORT = 9224;

export const DEV_BROWSER_CDP_PORT = 9225;

export const WHATSAPP_API_PORT = 9230;

export const PERMISSION_REQUEST_TIMEOUT_MS = 5 * 60 * 1000;

export const LOG_MAX_FILE_SIZE_BYTES = 50 * 1024 * 1024;
export const LOG_RETENTION_DAYS = 7;
export const LOG_BUFFER_FLUSH_INTERVAL_MS = 5000;
export const LOG_BUFFER_MAX_ENTRIES = 100;

export const MCP_TOOL_TIMEOUT_MS = 30000;

export const CONNECTOR_AUTH_REQUIRED_MARKER = '__MYBOTEAM_CONNECTOR_AUTH_REQUIRED__';
