import type { ProviderId, ProviderMeta } from './settings-types.js';

export const PROVIDER_META: Record<ProviderId, ProviderMeta> = {
  anthropic: {
    id: 'anthropic',
    name: 'Anthropic',
    category: 'classic',
    label: 'Service',
    logoKey: 'claude',
    helpUrl: 'https://console.anthropic.com/settings/keys',
  },
  openai: {
    id: 'openai',
    name: 'OpenAI',
    category: 'classic',
    label: 'Service',
    logoKey: 'open-ai',
    helpUrl: 'https://platform.openai.com/api-keys',
  },
  google: {
    id: 'google',
    name: 'Gemini',
    category: 'classic',
    label: 'Service',
    logoKey: 'google-gen-ai',
    helpUrl: 'https://aistudio.google.com/app/apikey',
  },
  xai: {
    id: 'xai',
    name: 'XAI',
    category: 'classic',
    label: 'Service',
    logoKey: 'Xai',
    helpUrl: 'https://x.ai/api',
  },
  deepseek: {
    id: 'deepseek',
    name: 'DeepSeek',
    category: 'classic',
    label: 'Service',
    logoKey: 'Deepseek',
    helpUrl: 'https://platform.deepseek.com/api_keys',
  },
  moonshot: {
    id: 'moonshot',
    name: 'Moonshot AI',
    category: 'classic',
    label: 'Service',
    logoKey: 'moonshot',
    helpUrl: 'https://platform.moonshot.ai/docs/guide/start-using-kimi-api',
  },
  zai: { id: 'zai', name: 'Z-AI', category: 'classic', label: 'Service', logoKey: 'z-ai' },
  bedrock: {
    id: 'bedrock',
    name: 'AWS Bedrock',
    category: 'aws',
    label: 'Service',
    logoKey: 'aws-bedrock',
  },
  vertex: { id: 'vertex', name: 'Vertex AI', category: 'gcp', label: 'Service', logoKey: 'vertex' },
  'azure-foundry': {
    id: 'azure-foundry',
    name: 'Azure AI Foundry',
    category: 'azure',
    label: 'Service',
    logoKey: 'azure',
    helpUrl: 'https://ai.azure.com',
  },
  ollama: {
    id: 'ollama',
    name: 'Ollama',
    category: 'local',
    label: 'Local Models',
    logoKey: 'olama',
  },
  openrouter: {
    id: 'openrouter',
    name: 'OpenRouter',
    category: 'proxy',
    label: 'Service',
    logoKey: 'open-router',
    helpUrl: 'https://openrouter.ai/keys',
  },
  litellm: {
    id: 'litellm',
    name: 'LiteLLM',
    category: 'hybrid',
    label: 'Service',
    logoKey: 'liteLLM',
  },
  minimax: {
    id: 'minimax',
    name: 'MiniMax',
    category: 'classic',
    label: 'Service',
    logoKey: 'minimax',
    helpUrl: 'https://platform.minimax.io/user-center/basic-information/interface-key',
  },
  lmstudio: {
    id: 'lmstudio',
    name: 'LM Studio',
    category: 'local',
    label: 'Local Models',
    logoKey: 'lmstudio',
    helpUrl: 'https://lmstudio.ai/',
  },
  'huggingface-local': {
    id: 'huggingface-local',
    name: 'HuggingFace Local',
    category: 'local',
    label: 'Local Models',
    logoKey: 'huggingface',
  },
  nebius: {
    id: 'nebius',
    name: 'Nebius AI',
    category: 'classic',
    label: 'Llama & DeepSeek models',
    logoKey: 'nebius',
    helpUrl: 'https://studio.nebius.ai/',
  },
  together: {
    id: 'together',
    name: 'Together AI',
    category: 'classic',
    label: 'Llama & Mixtral models',
    logoKey: 'together',
    helpUrl: 'https://api.together.xyz/settings/api-keys',
  },
  fireworks: {
    id: 'fireworks',
    name: 'Fireworks AI',
    category: 'classic',
    label: 'Fast inference models',
    logoKey: 'fireworks',
    helpUrl: 'https://fireworks.ai/account/api-keys',
  },
  groq: {
    id: 'groq',
    name: 'Groq',
    category: 'classic',
    label: 'Ultra-fast Llama models',
    logoKey: 'groq',
    helpUrl: 'https://console.groq.com/keys',
  },
  venice: {
    id: 'venice',
    name: 'Venice AI',
    category: 'classic',
    label: 'Service',
    logoKey: 'venice',
    helpUrl: 'https://venice.ai/settings/api',
  },
  nim: {
    id: 'nim',
    name: 'NVIDIA NIM',
    category: 'classic',
    label: 'NVIDIA-hosted models',
    logoKey: 'nim',
    helpUrl: 'https://org.ngc.nvidia.com/setup/api-key',
  },
  custom: {
    id: 'custom',
    name: 'Custom Endpoint',
    category: 'hybrid',
    label: 'Custom',
    logoKey: 'custom',
  },
  copilot: {
    id: 'copilot',
    name: 'GitHub Copilot',
    category: 'classic',
    label: 'Service',
    logoKey: 'github-copilot',
    helpUrl: 'https://github.com/settings/copilot',
  },
};
