export const DEFAULT_CONFIG_FILE_NAME = 'opencode.json';
export const BASH_PERMISSION_POLICY = {
  '*': 'allow',
  '* > *': 'ask',
  '* >> *': 'ask',
  '* 2> *': 'ask',
  '* | tee *': 'ask',
  '* && tee *': 'ask',
  'tee *': 'ask',
  'cat > *': 'ask',
  'rm *': 'ask',
  'mv *': 'ask',
  'cp *': 'ask',
  'mkdir *': 'ask',
  'touch *': 'ask',
  'chmod *': 'ask',
  'chown *': 'ask',
  'ln *': 'ask',
  'install *': 'ask',
  'truncate *': 'ask',
  'sed -i*': 'ask',
  'python*': 'ask',
  'node *': 'ask',
  'ruby *': 'ask',
  'perl *': 'ask',
  'sh *': 'ask',
  'bash *': 'ask',
  'zsh *': 'ask',
  'osascript *': 'ask',
  'curl * -o *': 'ask',
  'curl * --output *': 'ask',
  'wget *': 'ask',
  'tar *x*': 'ask',
  'unzip *': 'ask',
  'rsync *': 'ask',
} as const;
export const MYBOTEAM_PERMISSION_POLICY = {
  bash: BASH_PERMISSION_POLICY,
  edit: 'ask',
  write: 'ask',
  patch: 'ask',
  multiedit: 'ask',
  modify: 'ask',
  delete: 'ask',
  question: 'allow',
  todowrite: 'allow',
} as const;
export const MYBOTEAM_AGENT_NAME = 'myboteam';
