import type { ProviderConfig } from './provider-types.js';

export const DEFAULT_PROVIDERS: ProviderConfig[] = [
  {
    id: 'anthropic',
    name: 'Anthropic',
    requiresApiKey: true,
    apiKeyEnvVar: 'ANTHROPIC_API_KEY',
    defaultModelId: 'anthropic/claude-opus-4-5',
    modelsEndpoint: {
      url: 'https://api.anthropic.com/v1/models',
      authStyle: 'x-api-key',
      extraHeaders: { 'anthropic-version': '2023-06-01' },
      responseFormat: 'anthropic',
      modelIdPrefix: 'anthropic/',
      modelFilter: /^claude-/,
    },
    models: [],
  },
  {
    id: 'openai',
    name: 'OpenAI',
    requiresApiKey: true,
    apiKeyEnvVar: 'OPENAI_API_KEY',
    defaultModelId: 'openai/gpt-5.2',
    modelsEndpoint: {
      url: 'https://api.openai.com/v1/models',
      authStyle: 'bearer',
      responseFormat: 'openai',
      modelIdPrefix: 'openai/',
      modelFilter: /^gpt-|^o[134]|^chatgpt-/,
    },
    models: [],
  },
  {
    id: 'google',
    name: 'Google AI',
    requiresApiKey: true,
    apiKeyEnvVar: 'GOOGLE_GENERATIVE_AI_API_KEY',
    defaultModelId: 'google/gemini-3-pro-preview',
    modelsEndpoint: {
      url: 'https://generativelanguage.googleapis.com/v1beta/models',
      authStyle: 'query-param',
      responseFormat: 'google',
      modelIdPrefix: 'google/',
    },
    models: [],
  },
  {
    id: 'xai',
    name: 'xAI',
    requiresApiKey: true,
    apiKeyEnvVar: 'XAI_API_KEY',
    baseUrl: 'https://api.x.ai',
    defaultModelId: 'xai/grok-4',
    modelsEndpoint: {
      url: 'https://api.x.ai/v1/models',
      authStyle: 'bearer',
      responseFormat: 'openai',
      modelIdPrefix: 'xai/',
    },
    models: [],
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    requiresApiKey: true,
    apiKeyEnvVar: 'DEEPSEEK_API_KEY',
    baseUrl: 'https://api.deepseek.com',
    defaultModelId: 'deepseek/deepseek-chat',
    modelsEndpoint: {
      url: 'https://api.deepseek.com/models',
      authStyle: 'bearer',
      responseFormat: 'openai',
      modelIdPrefix: 'deepseek/',
    },
    models: [],
  },
  {
    id: 'moonshot',
    name: 'Moonshot AI',
    requiresApiKey: true,
    apiKeyEnvVar: 'MOONSHOT_API_KEY',
    baseUrl: 'https://api.moonshot.ai/v1',
    defaultModelId: 'moonshot/kimi-k2.5',
    modelsEndpoint: {
      url: 'https://api.moonshot.ai/v1/models',
      authStyle: 'bearer',
      responseFormat: 'openai',
      modelIdPrefix: 'moonshot/',
    },
    models: [],
  },
  {
    id: 'zai',
    name: 'Z.AI Coding Plan',
    requiresApiKey: true,
    apiKeyEnvVar: 'ZAI_API_KEY',
    baseUrl: 'https://open.bigmodel.cn',
    defaultModelId: 'zai/glm-4.7-flashx',
    modelsEndpoint: {
      url: 'https://open.bigmodel.cn/api/paas/v4/models',
      authStyle: 'bearer',
      responseFormat: 'openai',
      modelIdPrefix: 'zai/',
    },
    models: [
      {
        id: 'glm-5',
        displayName: 'GLM-5',
        provider: 'zai',
        fullId: 'zai/glm-5',
        contextWindow: 128000,
        supportsVision: false,
      },
    ],
  },
  {
    id: 'bedrock',
    name: 'Amazon Bedrock',
    requiresApiKey: false,
    models: [],
  },
  {
    id: 'vertex',
    name: 'Google Vertex AI',
    requiresApiKey: false,
    models: [],
  },
  {
    id: 'minimax',
    name: 'MiniMax',
    requiresApiKey: true,
    apiKeyEnvVar: 'MINIMAX_API_KEY',
    baseUrl: 'https://api.minimax.io/v1',
    editableBaseUrl: true,
    defaultModelId: 'minimax/MiniMax-M2.5',
    models: [
      {
        id: 'MiniMax-M2',
        displayName: 'MiniMax M2',
        provider: 'minimax',
        fullId: 'minimax/MiniMax-M2',
        contextWindow: 196608,
        supportsVision: false,
      },
      {
        id: 'MiniMax-M2.1',
        displayName: 'MiniMax M2.1',
        provider: 'minimax',
        fullId: 'minimax/MiniMax-M2.1',
        contextWindow: 204800,
        supportsVision: false,
      },
      {
        id: 'MiniMax-M2.1-highspeed',
        displayName: 'MiniMax M2.1 Highspeed',
        provider: 'minimax',
        fullId: 'minimax/MiniMax-M2.1-highspeed',
        contextWindow: 204800,
        supportsVision: false,
      },
      {
        id: 'MiniMax-M2.5',
        displayName: 'MiniMax M2.5',
        provider: 'minimax',
        fullId: 'minimax/MiniMax-M2.5',
        contextWindow: 204800,
        supportsVision: false,
      },
      {
        id: 'MiniMax-M2.5-highspeed',
        displayName: 'MiniMax M2.5 Highspeed',
        provider: 'minimax',
        fullId: 'minimax/MiniMax-M2.5-highspeed',
        contextWindow: 204800,
        supportsVision: false,
      },
    ],
  },
  {
    id: 'nebius',
    name: 'Nebius AI',
    requiresApiKey: true,
    apiKeyEnvVar: 'NEBIUS_API_KEY',
    baseUrl: 'https://api.studio.nebius.ai/v1',
    modelsEndpoint: {
      url: 'https://api.studio.nebius.ai/v1/models',
      authStyle: 'bearer',
      responseFormat: 'openai',
      modelIdPrefix: 'nebius/',
    },
    models: [],
    defaultModelId: 'nebius/meta-llama/Meta-Llama-3.1-70B-Instruct',
  },
  {
    id: 'together',
    name: 'Together AI',
    requiresApiKey: true,
    apiKeyEnvVar: 'TOGETHER_API_KEY',
    baseUrl: 'https://api.together.xyz/v1',
    modelsEndpoint: {
      url: 'https://api.together.xyz/v1/models',
      authStyle: 'bearer',
      responseFormat: 'openai',
      modelIdPrefix: 'together/',
    },
    models: [],
    defaultModelId: 'together/meta-llama/Llama-3-70b-chat-hf',
  },
  {
    id: 'fireworks',
    name: 'Fireworks AI',
    requiresApiKey: true,
    apiKeyEnvVar: 'FIREWORKS_API_KEY',
    baseUrl: 'https://api.fireworks.ai/inference/v1',
    modelsEndpoint: {
      url: 'https://api.fireworks.ai/inference/v1/models',
      authStyle: 'bearer',
      responseFormat: 'openai',
      modelIdPrefix: 'fireworks/',
    },
    models: [],
    defaultModelId: 'fireworks/accounts/fireworks/models/llama-v3-70b-instruct',
  },
  {
    id: 'groq',
    name: 'Groq',
    requiresApiKey: true,
    apiKeyEnvVar: 'GROQ_API_KEY',
    baseUrl: 'https://api.groq.com/openai/v1',
    modelsEndpoint: {
      url: 'https://api.groq.com/openai/v1/models',
      authStyle: 'bearer',
      responseFormat: 'openai',
      modelIdPrefix: 'groq/',
    },
    models: [],
    defaultModelId: 'groq/llama3-70b-8192',
  },
  {
    id: 'venice',
    name: 'Venice AI',
    requiresApiKey: true,
    apiKeyEnvVar: 'VENICE_API_KEY',
    baseUrl: 'https://api.venice.ai/api/v1',
    defaultModelId: 'venice/llama-3.3-70b',
    modelsEndpoint: {
      url: 'https://api.venice.ai/api/v1/models',
      authStyle: 'bearer',
      responseFormat: 'openai',
      modelIdPrefix: 'venice/',
    },
    models: [],
  },
  {
    id: 'copilot',
    name: 'GitHub Copilot',
    requiresApiKey: false,
    defaultModelId: 'copilot/gpt-4o',
    models: [],
  },
  {
    id: 'myboteam-ai',
    name: 'MyBoTeam AI',
    requiresApiKey: false,
    defaultModelId: 'myboteam-ai/myboteam-free',
    models: [
      {
        id: 'myboteam-free',
        displayName: 'MyBoTeam',
        provider: 'myboteam-ai',
        fullId: 'myboteam-ai/myboteam-free',
        contextWindow: 128_000,
        maxOutputTokens: 32_000,
        supportsVision: true,
      },
    ],
  },
];
